version: '3'
 
services:
  app:
    build:
      context:  .
      dockerfile: Dockerfile
    expose:
      - "5000"
  proxy:
    build:
      context:  ./nginx
      dockerfile: Dockerfile
    ports:
      - "80:80"
    links:
      - app